version: 2.1

executors:
  build-executor:
    docker:
      - image: opennms/build-env:1.0-b6
  docker-executor:
    docker:
      - image: docker:18
  smoke-test-executor:
    machine: true

commands:
  cached-checkout:
      description: "Checkout with caching"
      steps:
        - restore_cache:
            keys:
              - source-v1-{{ .Branch }}-{{ .Revision }}
              - source-v1-{{ .Branch }}-
              - source-v1-
        - checkout
        - save_cache:
            key: source-v1-{{ .Branch }}-{{ .Revision }}
            paths:
              - ".git"

  restore-maven-cache:
      description: "Calculate cache key and restore cache"
      steps:
        - run: 
            name: Calculate cache key from pom files
            command: |
              find . -type f -name "pom.xml" -exec sha256sum "{}" \; >> maven-dependency-cache.key
        - restore_cache:
            keys:
              - maven-dependencies-v2-{{ checksum "maven-dependency-cache.key" }}
              - maven-dependencies-v2-
        - run:
            name: Remove OpenNMS artifacts from cache
            command: |
              rm -rf ~/.m2/repository/org/opennms

  save-maven-cache:
    description: "Save Maven dependency cache"
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-v2-{{ checksum "maven-dependency-cache.key" }}

  dockerhub-login:
    description: "Connect to DockerHub"
    steps:
      - run:
          name: Login to DockerHub
          command: |
            docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASS}
  
  bash-alpine:
    description: "Add bash support in Alpine based images"
    steps:
      - run:
          name: Add bash support
          command: |
            apk add --no-cache bash

workflows:
  build-deploy:
    jobs:
      - build
      - build-horizon-oci:
          requires:
            - build
      - build-minion-oci:
          requires:
            - build
      - build-sentinel-oci:
          requires:
            - build
      - publish-horizon-oci:
          requires:
            - build-horizon-oci
      - smoke-test:
          requires:
            - build

jobs:
  build:
    executor: build-executor
    # Building currently requires the xlarge containers in order for the webpack compilation
    # in the core/web-assets module to complete reliably
    resource_class: xlarge
    steps:
      - cached-checkout
      - restore-maven-cache
      - run:
          name: Compile
          command: |
            mvn clean -DskipTests=true
            ./compile.pl -DskipTests=true -Dbuild.skip.tarball=true
      - run:
          name: Build RPMs
          command: |
            ./makerpm.sh -a -d
      - save-maven-cache
      - store_artifacts:
          path: ~/project/target/rpm/RPMS/noarch
          destination: rpms
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  
  build-horizon-oci:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - bash-alpine
      - run:
          name: Fetch RPM artifacts and build Horizon container image
          command: |
            cd opennms-container/horizon
            ./fetch-rpms.sh
            ./build_container_image.sh
      - store_artifacts:
          path: ~/project/opennms-container/horizon/images/container.oci
          destination: horizon.oci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build-minion-oci:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - bash-alpine
      - run:
          name: Fetch RPM artifacts and build Minion container image
          command: |
            cd opennms-container/minion
            ./fetch-rpms.sh
            ./build_container_image.sh
      - store_artifacts:
          path: ~/project/opennms-container/minion/images/container.oci
          destination: minion.oci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build-sentinel-oci:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - bash-alpine
      - run:
          name: Fetch RPM artifacts and build Sentinel container image
          command: |
            cd opennms-container/sentinel
            ./fetch-rpms.sh
            ./build_container_image.sh
      - store_artifacts:
          path: ~/project/opennms-container/sentinel/images/container.oci
          destination: sentinel.oci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  smoke-test:
    executor: smoke-test-executor
    steps:
      - attach_workspace:
          at: ~/
      # Link root user's m2 repo from the cache with our user's m2 repo (the circleci user)
      - run:
          name: Link maven repo with cache
          command: |
            sudo chmod 777 /root
            ln -s /root/.m2 ~/.m2
      - restore-maven-cache
      - run:
          name: Smoke Tests
          command: |
            .circleci/scripts/smoke.sh

  publish-horizon-oci:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - bash-alpine
      - run:
          name: Load Horizon OCI image, tag it and publish to registry
          command: 
            cd opennms-container/horizon
            docker image load -i images/container.oci
            ./tag.sh
            ./publish.sh
